### ISSUE TITLE
スレッドの閲覧機能（frontend）

### ISSUE THREAD

**Issue by zisui-sukitarou** [givery-bootcamp/dena-2024-team11#15]
## 概要
* メッセージをクリックすると、そのメッセージに対するコメントが閲覧できる（Slackのスレッド機能のようなもの）

**Comment by Tanichael** [comment]
進め方
- global変数をスレッドに対応させる
- reply用のapiを作成 
  - バックエンド側のAPIを確認したい
- reply用にactionやreducerを作成
- 見た目を調整する

**Comment by Tanichael** [comment]
- スレッドを切り替えられるようにする
- APIの差し替え
