### ISSUE TITLE
投稿一覧画面の実装

### ISSUE THREAD

**Issue by tone8151** [givery-bootcamp/dena-2024-team11#2]
## frontend
- ルーティング: `/`

### 画面サンプル
![image](https://github.com/givery-bootcamp/dena-2024-team11/assets/68996392/1407ff68-e38f-4d39-8e4d-f907487c7692)
- 画面のどこかにメニューを配置して、クリックしたら「トップ（＝投稿一覧）」に遷移するようにしてください。
- アクセスされたらAPIを呼び出して投稿一覧を表示させてください。表示順はAPIレスポンスの順で構いません。
  - APIの呼び出しはfetchでOKです。他に使い慣れたライブラリなどあればそれでもOKです。
- 投稿一覧には「タイトル」「ユーザー名」「更新日時」を表示させてください。
- [投稿詳細画面](https://github.com/givery-bootcamp/training-app-2024/issues/3)の作成後は投稿のどこかをクリックしたら、投稿詳細に移動するようにしてください。
 
## ヒント
- redux使うの慣れてない人はAPIの非同期処理とStoreの連結に苦戦するかもしれません。createAsyncThunkをうまく使ってAPIの処理をextraReducersに繋いでみましょう。このあたりの処理はSPA作成の中でも重要な概念です、ここで理解しておけば他のライブラリでも同様のメンタルマップを利用できます。
  - https://redux-toolkit.js.org/api/createAsyncThunk
 
## 参考
- [元issue](https://github.com/givery-bootcamp/training-app-2024/issues/7#issue-2255670180)

## memo
- 投稿一覧のテーブル自体はReactのTutorialの[Reactの流儀](https://ja.react.dev/learn/thinking-in-react)で学べそう

**Comment by zisui-sukitarou** [comment]
仮置きで作ったissueのため削除
