### ISSUE TITLE
投稿詳細APIの実装

### ISSUE THREAD

**Issue by kawamii** [givery-bootcamp/dena-2024-team11#3]
### backend
- endpoint: GET /posts/:postId
- parameters: なし
- response: Postエンティティ
- 認証: 不要
### ヒント
PostRepositoryではlistメソッドとgetメソッドは別に定義してください。
ただ、実装的にはlistメソッドをOptionalで指定のidで検索できるようにしてgetメソッドはそれを呼び出すだけとする方がシンプルになります。
### 参考
- [元 issue](https://github.com/givery-bootcamp/training-app-2024/issues/3)

**Comment by zisui-sukitarou** [comment]
仮置きで作ったissueのため削除
