### ISSUE TITLE
投稿一覧画面のページング

### ISSUE THREAD

**Issue by pokeshun96** [givery-bootcamp/dena-2024-team11#5]
## frontend
- 画面下部にページネーションコンポーネントを配置してページを切り替えられるようにしてください
    - 1ページの件数は自由です。画面どこかで指定できるようにしても構いません。
- 2ページ目以降を表示中のURLは `/?page=2`のようにクエリでページが指定されている体裁を取り、リロードしてもページが切り替わらないようにしてください。
    - このタスクは更にオプショナルでも構いません。同時に考えるより先にページネーションコンポーネントだけを追加したほうが良いと思います。

## 参考
[元issue](https://github.com/givery-bootcamp/training-app-2024/issues/4)

**Comment by zisui-sukitarou** [comment]
仮置きで作ったissueのため削除
